#!/bin/sh

chmod u+x ./installaitions
chmod u+x ./this_setting

sudo ./installaitions

cd package_manager
chmod u+x ./build_*
chmod u+x ./deploy_*
cd ..
cd mypersonaldockeruse
chmod u+x ./build_this_pkg
cd ..
cd mypersonaldockerusexample
chmod u+x ./x
cd ..
chmod u+x ./x

python -m venv .venv
. ./myvenv
pip download mydockeruse
pip install mydockeruse