#!/bin/sh
cd package_manager
chmod u+x build_*
chmod u+x deploy_*
cd ..
cd mypersonaldockeruse
chmod u+x this*
cd ..

python -m venv .venv
. myvenv
pip download -y mydockeruse
pip install -y mydockeruse