name: mypersonaldockeruse
version: 0.0.1
summary: PyPI mydockeruse pkg install env ultimit-installer
description: using PyPI mydockertool package much better in docker by PyPI mypersonaldockeruse, and also it deploy as snap & apt with build-essential & python also deploy as docker 2 use much better.

grade: edge
confinement: strict

parts:
	python3:
		plugin: nil
		stage-packages:
			- python3
			- python3-pip
	
	docker:
		plugin: nil
		stage-packages:
			- docker.io
	
	mypersonaldockertool:
		plugin: python
		python-version: pytho3
		pip:
			- mypersonaldockertool