name: mypersonaldockeruse
version: 0.0.1
summary: ㅣpassㅣ
description: ㅣpassㅣ

grade: edge
confinement: strict

parts:
	python3:
		plugin: nil
		stage-packages:
			- python3
			- python3-pip
	
	docker:
		plugin: nil
		stage-packages:
			- docker.io
	
	mypersonaldockertool:
		plugin: python
		python-version: pytho3
		pip:
			- mypersonaldockertool